# Generated by Django 5.0.3 on 2026-04-02 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_subscription', models.BooleanField(default=False, verbose_name='Проверять подписку')),
                ('channel_id', models.CharField(blank=True, max_length=100, verbose_name='ID канала или юзернейм (@channel)')),
                ('channel_url', models.URLField(blank=True, help_text="Для кнопки 'Перейти в канал'", verbose_name='Ссылка на канал')),
                ('payment_details', models.TextField(blank=True, verbose_name='Реквизиты для оплаты')),
            ],
            options={
                'verbose_name': 'Настройки бота',
                'verbose_name_plural': 'Настройки бота',
            },
        ),
        migrations.CreateModel(
            name='MessageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='1 - первое сообщение, 2 - второе и т.д.', unique=True, verbose_name='Порядок шага')),
                ('text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('media', models.FileField(blank=True, null=True, upload_to='steps/', verbose_name='Медиафайл (Фото/Видео/Аудио/Документ)')),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='0 - отправить сразу после предыдущего шага', verbose_name='Задержка перед отправкой (в минутах)')),
            ],
            options={
                'verbose_name': 'Шаг воронки',
                'verbose_name_plural': 'Цепочка сообщений (Воронка)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Юзернейм')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Подписан на канал?')),
                ('has_paid', models.BooleanField(default=False, verbose_name='Оплатил доступ?')),
                ('next_step_time', models.DateTimeField(blank=True, null=True, verbose_name='Время следующего сообщения')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='telegram_bot.messagestep', verbose_name='Текущий шаг')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.CharField(max_length=255, verbose_name='File ID чека (Telegram)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Квитанция об оплате',
                'verbose_name_plural': 'Квитанции об оплате',
            },
        ),
    ]
