# Generated by Django 5.0.3 on 2026-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='receipt_image',
            field=models.FileField(upload_to='receipts/', verbose_name='Скриншот чека'),
        ),
    ]
