# Generated by Django 5.0.3 on 2026-04-02 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_paymentreceipt_receipt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDailyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст напоминания')),
                ('media', models.FileField(blank=True, null=True, upload_to='reminders/', verbose_name='Медиафайл (Фото/Видео/Документ)')),
                ('send_time', models.TimeField(verbose_name='Время ежедневной отправки')),
            ],
            options={
                'verbose_name': 'Системное напоминание',
                'verbose_name_plural': 'Системные ежедневные напоминания (Для всех)',
                'ordering': ['send_time'],
            },
        ),
        migrations.AddField(
            model_name='messagestep',
            name='days_delay',
            field=models.PositiveIntegerField(default=0, help_text='0 = в этот же день, 1 = на следующий день после предыдущего шага.', verbose_name='Через сколько дней (для точного времени)'),
        ),
        migrations.AddField(
            model_name='messagestep',
            name='exact_time',
            field=models.TimeField(blank=True, help_text='Если указано, бот проигнорирует задержку в минутах и отправит сообщение ровно в это время.', null=True, verbose_name='Точное время отправки'),
        ),
        migrations.AlterField(
            model_name='messagestep',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0, help_text='0 - отправить сразу. (Игнорируется, если задано Точное время)', verbose_name='Задержка перед отправкой (в минутах)'),
        ),
        migrations.CreateModel(
            name='UserPersonalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст напоминания')),
                ('remind_at', models.DateTimeField(verbose_name='Когда напомнить')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Личное напоминание пользователя',
                'verbose_name_plural': 'Личные напоминания от пользователей',
            },
        ),
        migrations.CreateModel(
            name='SystemReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField(verbose_name='Дата отправки')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.systemdailyreminder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.botuser')),
            ],
            options={
                'unique_together': {('user', 'reminder', 'date_sent')},
            },
        ),
    ]
